#!/usr/bin/python
import pyray as pr
import os as os
import json as json
# imports

#gets val form a dict if its key exists, otherwise uses a default val
def getConfigVal(dictFrom: dict, defaultVal, key: str):
    return defaultVal if not key in dictFrom else dictFrom[key]

PYRAY_COLORS = {
    "darkgray" : pr.DARKGRAY,
    "maroon" : pr.MAROON,
    "orange" : pr.ORANGE,
    "darkgreen" : pr.DARKGREEN,
    "darkblue" : pr.DARKBLUE,
    "darkpurple" : pr.DARKPURPLE,
    "darkbrown" : pr.DARKBROWN,
    "gray" : pr.GRAY,
    "red" : pr.RED,
    "gold" : pr.GOLD,
    "lime" : pr.LIME,
    "blue" : pr.BLUE,
    "violet" : pr.VIOLET,
    "brown" : pr.BROWN,
    "lightgray" : pr.LIGHTGRAY,
    "pink" : pr.PINK,
    "yellow" : pr.YELLOW,
    "green" : pr.GREEN,
    "skyblue" : pr.SKYBLUE,
    "purple" : pr.PURPLE,
    "beige" : pr.BEIGE,
    "black" : pr.BLACK,
    "white" : pr.WHITE
}

#config vars
CONFIG_LOCATION = "config.json"

CONFIG = {}

try:
    config_file = open(CONFIG_LOCATION, "r")
    CONFIG = json.load(config_file)
    config_file.close()
except:
    print("exception")

COMMANDS = getConfigVal(CONFIG, [], "entries")

FONT_SRC = getConfigVal(CONFIG, "", "font")

FONT_SIZE = getConfigVal(CONFIG, 20, "font_size")
LETTER_SPACING = getConfigVal(CONFIG, 2, "letter_spacing")
CMD_SPACING = getConfigVal(CONFIG, 4, "cmd_spacing")

SCREEN_WIDTH = getConfigVal(CONFIG, 400, "screen_width")
SCREEN_HEIGHT = getConfigVal(CONFIG, 200, "screen_height")

LEFT_GAP = getConfigVal(CONFIG, 14, "left_gap")
TOP_GAP = getConfigVal(CONFIG, 14, "top_gap")
RIGHT_GAP = getConfigVal(CONFIG, 4, "right_gap")
BOTTOM_GAP = getConfigVal(CONFIG, 14, "bottom_gap")

LEFT_BORDER = getConfigVal(CONFIG, 4, "left_border")
TOP_BORDER = getConfigVal(CONFIG, 4, "top_border")
RIGHT_BORDER = getConfigVal(CONFIG, 4, "right_border")
BOTTOM_BORDER = getConfigVal(CONFIG, 4, "bottom_border")

BAR_TOP_GAP = getConfigVal(CONFIG, 4, "bar_top_gap")
BAR_HEIGHT = getConfigVal(CONFIG, 4, "bar_height")
BAR_BOTTOM_GAP = getConfigVal(CONFIG, 4, "bar_bottom_gap")

TOTAL_BAR_HEIGHT = BAR_TOP_GAP + BAR_BOTTOM_GAP + BAR_HEIGHT

DOT_SIZE = getConfigVal(CONFIG, 8, "dot_size")
DOT_GAP_LEFT = getConfigVal(CONFIG, 6, "dot_gap_left")
DOT_GAP_TOP = getConfigVal(CONFIG, 6, "dot_gap_top")

INPUT_OFFSET = getConfigVal(CONFIG, 2, "input_offset")
COMMAND_OFFSET = getConfigVal(CONFIG, 20, "command_offset")

NO_INPUT_TEXT = getConfigVal(CONFIG, "Enter text", "no_input_text")
MAX_INPUT_LEN = getConfigVal(CONFIG, 18, "max_input_len")

CURSOR_ON_TIME = getConfigVal(CONFIG, 45, "cursor_on_time")
CURSOR_OFF_TIME = getConfigVal(CONFIG, 45, "cursor_off_time")

DEFAULT_COLORS = {
    "background": "black",
    "border": "darkgray",
    "input": "lightgray",
    "no_input": "darkgray",
    "bar": "darkgray",
    "dot": "darkgray",
    "selected_cmd": "lightgray",
    "unselected_cmd": "gray",
    "no_cmd": "darkgray"
}

COLORS = getConfigVal(CONFIG, DEFAULT_COLORS, "colors")

BACKGROUND_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["background"], "background")
]

BORDER_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["border"], "border")
]

INPUT_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["input"], "input")
]

NO_INPUT_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["no_input"], "no_input")
]

BAR_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["bar"], "bar")
]

DOT_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["dot"], "dot")
]

SELECTED_CMD_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["selected_cmd"], "selected_cmd")
]

UNSELECTED_CMD_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["unselected_cmd"], "unselected_cmd")
]

NO_CMD_COLOR = PYRAY_COLORS[
    getConfigVal(COLORS, DEFAULT_COLORS["no_cmd"], "no_cmd")
]

# adds char to input_str given by char code in temp
def add_char_to_cmd(temp: int, input_str: str) -> str:
    if temp == pr.KeyboardKey.KEY_BACKSPACE:
        # deletes last char if backspace is pressed

        if len(input_str) > 0:
            input_str = input_str[:len(input_str) - 1]

    elif (pr.KeyboardKey.KEY_A <= temp <= pr.KeyboardKey.KEY_Z) or\
        pr.KeyboardKey.KEY_ZERO <= temp <= pr.KeyboardKey.KEY_NINE:
        # otherwise adds char to input_str
        input_str += chr(temp).lower();
    return input_str

# sorts a list of list of strings based on how similar an input string is to
# the first string in each list in the list var
def sort_cmd_list(input_str: str, cmd_list: list) -> list:

    temp: list = []

    for elem in cmd_list:
        segment: str = ""
        longest_substr: int = 0
        substr_at: int = len(elem[0])
        for char in input_str:
            substr: str = ""
            segment += char
            for i in range(len(segment)):
                substr = segment[i:]
                temp_sub_at: int = elem[0].find(substr)
                if not temp_sub_at == -1:
                    longest_substr += len(substr)
                    if temp_sub_at < substr_at:
                        substr_at = temp_sub_at

        if len(temp) == 0:
            temp.append([longest_substr, substr_at, elem])
        else:
            for i in range(len(temp)):
                if (temp[i][0] < longest_substr) or \
                    ((temp[i][0] == longest_substr) and \
                    (temp[i][1] > substr_at)) or ( \
                    (temp[i][0] == longest_substr) and ( \
                    (temp[i][1] == substr_at) and \
                    (len(temp[i][2][0]) > len(elem[0])))):
                    temp.insert(i, [longest_substr, substr_at, elem])
                    break
                if i == len(temp) - 1:
                    temp.append([longest_substr, substr_at, elem])

    for i in range(len(temp)):
        temp[i] = temp[i][2]

    return temp

def main():
    input_str: str = ""

    # tracks input time
    input_time: int = 0

    # what input is selected
    input_num_selected: int = 0
    # creates window
    pr.init_window(SCREEN_WIDTH, SCREEN_HEIGHT, "")

    # all the keys that are down
    keysDown: list = list()

    # sets target fps and counts frames
    pr.set_target_fps(60)
    frame_num: int = 0

    # frame loop
    while not pr.window_should_close():
        menu_font = pr.load_font(FONT_SRC)

        # NOTE: drawing start
        pr.begin_drawing()

        pr.clear_background(BACKGROUND_COLOR)

        # gets next char in queue
        temp: int = pr.get_key_pressed()

        # loops if char queue is not empty
        if not temp == 0:

            input_time = frame_num

            # checks if char is pressed
            while True:

                # makes list of all keys down

                keysDown.append(temp)

                # selects which command to input
                if temp == pr.KeyboardKey.KEY_DOWN:
                    input_num_selected += 1
                elif temp ==pr.KeyboardKey.KEY_UP:
                    input_num_selected -= 1
                else:
                    # adds key to input
                    input_str = add_char_to_cmd(temp, input_str)
                    if not pr.is_key_pressed(pr.KeyboardKey.KEY_ENTER):
                        input_num_selected = 0 if input_str == "" else 1

                # gets next char in queue
                temp: int = pr.get_key_pressed()

                # ends loop when char queue is empty
                if temp == 0:
                    keysDown = list(set(keysDown))
                    break
        # logic for repeated key presses
        elif (((frame_num - input_time) % 3) == 0) and \
            ((frame_num - input_time) > 30):
            newList: list = list()

            # filter keys no longer down
            for temp in keysDown:
                if pr.is_key_down(temp):
                    newList.append(temp)

            keysDown = newList

            for temp in keysDown:
                # selects which command to input
                if temp == pr.KeyboardKey.KEY_DOWN:
                    input_num_selected += 1
                elif temp ==pr.KeyboardKey.KEY_UP:
                    input_num_selected -= 1
                else:
                    #adds to input
                    input_str = add_char_to_cmd(temp, input_str)
                    if not pr.is_key_pressed(pr.KeyboardKey.KEY_ENTER):
                        input_num_selected = 0 if input_str == "" else 1

        if len(input_str) > MAX_INPUT_LEN:
            input_str = input_str[:MAX_INPUT_LEN]

        cmd_list = sort_cmd_list(input_str, COMMANDS)

        if input_str != "":
            cmd_list.insert(0, [input_str])

        # maximum num of elems that can be on-screen
        max_elems: int = max(
            (
                (pr.get_screen_height() -
                    (TOP_GAP + FONT_SIZE * 2 + TOTAL_BAR_HEIGHT + BOTTOM_GAP)
                ) // (FONT_SIZE + CMD_SPACING)),
                0
            )

        # offset of how many entries get deleted if max elems is less that input
        # num selected
        input_offset: int = 0

        # bounds input selection
        if input_num_selected < 0:
            input_num_selected = 0
        elif input_num_selected >= len(cmd_list):
            input_num_selected = len(cmd_list) - 1

        if input_num_selected > max_elems:
            cmd_list = cmd_list[(input_num_selected - max_elems):]
            input_offset = input_num_selected - max_elems
            input_num_selected -= input_offset

        # prints selected item to stdout
        if pr.is_key_pressed(pr.KeyboardKey.KEY_ENTER):
            pr.end_drawing()
            pr.close_window()
            print(cmd_list[input_num_selected][
                len(cmd_list[input_num_selected]) - 1])
            exit()

        # draws input
        pr.draw_text_ex(
            menu_font,
            (NO_INPUT_TEXT if input_str == "" else input_str.upper()) +
            ("_ "," ")[frame_num % (CURSOR_OFF_TIME + CURSOR_ON_TIME) >
            CURSOR_ON_TIME],
            (LEFT_GAP + INPUT_OFFSET, TOP_GAP),
            FONT_SIZE,
            LETTER_SPACING,
            NO_INPUT_COLOR if input_str == "" else INPUT_COLOR
        )

        pr.draw_rectangle(
            LEFT_GAP,
            TOP_GAP + FONT_SIZE + BAR_TOP_GAP,
            pr.get_screen_width() - LEFT_GAP - RIGHT_GAP,
            BAR_HEIGHT,
            BAR_COLOR
        )

        if len(cmd_list) > 0:
            pr.draw_rectangle(
                LEFT_GAP + DOT_GAP_LEFT,
                TOP_GAP + FONT_SIZE + TOTAL_BAR_HEIGHT + DOT_GAP_TOP +
                ((FONT_SIZE + CMD_SPACING) * input_num_selected),
                DOT_SIZE,
                DOT_SIZE,
                DOT_COLOR
            )

        for i in range(max_elems + 1):

            x = LEFT_GAP + COMMAND_OFFSET + DOT_GAP_LEFT
            y = (FONT_SIZE + CMD_SPACING) * i + TOTAL_BAR_HEIGHT + \
            FONT_SIZE + TOP_GAP
            text: str = "---"
            color = NO_CMD_COLOR

            #draws options
            if i < len(cmd_list):
                text = cmd_list[i][0]
                if len(cmd_list[i]) > 1:
                    if not cmd_list[i][1] == "":
                        text += f" ({cmd_list[i][1]})"

                if i == input_num_selected:
                    color = SELECTED_CMD_COLOR 
                else:
                    color = UNSELECTED_CMD_COLOR

            pr.draw_text_ex(
                menu_font,
                text,
                (x, y),
                FONT_SIZE,
                LETTER_SPACING,
                color
            )

        pr.draw_rectangle(
            0,
            0,
            pr.get_screen_width(),
            TOP_BORDER,
            BORDER_COLOR
        )

        pr.draw_rectangle(
            0,
            0,
            LEFT_BORDER,
            pr.get_screen_height(),
            BORDER_COLOR
        )

        pr.draw_rectangle(
            0,
            pr.get_screen_height() - BOTTOM_BORDER,
            pr.get_screen_width(),
            BOTTOM_BORDER,
            BORDER_COLOR
        )

        pr.draw_rectangle(
            pr.get_screen_width() - RIGHT_BORDER,
            0,
            RIGHT_BORDER,
            pr.get_screen_height(),
            BORDER_COLOR
        )

        # NOTE: drawing end
        pr.end_drawing()

        input_num_selected += input_offset

        frame_num += 1

        pr.unload_font(menu_font)
    # ends window
    pr.close_window()

if __name__ == '__main__':
    pr.set_trace_log_level(pr.TraceLogLevel.LOG_NONE)
    main()
